from fastapi import APIRouter, Depends, HTTPException
from app.core.auth import get_current_user
from app.agents.quote_agent import quote_agent

router = APIRouter()

@router.get("/daily")
async def get_daily_quote(user_id: str = Depends(get_current_user)):
    """
    Get a daily sustainability quote and tip generated by AI.
    """
    try:
        return await quote_agent()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
